<?php
$array = [
"top_title"=> "Futurastro",
"h1"=> 'The most shocking and accurate horoscopes, it will give you goosebumps',
"p_head"=> 'Choose your zodiac sign',
"aries"=> 'Aries',
"taurus"=> 'Taurus',
"gemini"=> 'Gemini',
"cancer"=> 'Cancer',
"leo"=> 'Leo',
"virgo"=> 'Virgo',
"libra"=> 'Libra',
"scorpio"=> 'Scorpio',
"sagitar"=> 'Sagittarius',
"capricorn"=> 'Capricorn',
"aquarius"=> 'Aquarius',
"pisces"=> 'Pisces',
"h2_gender"=> 'What is your gender?',
"back"=> 'Back',
"man"=> 'Man',
"woman"=> 'Woman',

"h2_born"=> 'Well! When were you born?',
"day_born"=> 'Day',
"month_born"=> "Month",
"year_born"=> 'Year',
"error"=> 'Please indicate the full date',
"p_help"=> 'This will help make your clairvoyance more precise.',
"continue"=> 'CONTINUE',


"h2_consern"=> 'What are your concerns?',
"work"=> 'Work',
"money"=> 'Finance',
"happy"=> 'Happy',
"love"=> "Love",
"heart"=> "Heart pain",
"family"=> 'Family',
"just"=> 'Justice',
"change"=> 'Change',
"general"=> 'General',

"h2_name"=> "What's your name?",
"h2_personal"=> "Where do you want to get your personalized clairvoyance?",
"confirm"=> "I hereby confirm that am of legal age and I agree to the privacy policy and terms of use.",
"mail"=> "E-mail",
"rules"=> "Please agree to the rules",
"button_free"=> "Get my complete clairvoyance for FREE",
"confidentality"=> "Your information is used confidentiality to create personalized clairvoyance.",
"user_fb"=>  "Jennifer",
"fback"=> "Thank you <br>Dear Athena, you have made a new person out of me, thank you very much again for everything!",
"home"=> "HOME",
"terms"=> "Terms of service",
"privacy"=> "Privacy policy",
"faq"=> "FAQ",
"mail_error"=> 'Please enter the correct email.',

//step8 final
"thank_p"=> 'Thank you for your answers!',
"receive_data"=> 'I received all your data and I am creating your unique ',
"receive_data_span"=> 'personalised reading',
"to_confirm"=> 'To confirm that you want to receive this reading please click on the button below and send us the sms to confirm.',
"button_get" => 'I want to get my unique reading',
"city_question" => "In which town/city are you born?",
"city"=> 'Please enter your city',
//time
"time_question"=> "Do you know what time you were born?",
"yes"=> "Yes",
"no"=> "No",
"time"=> "Please enter hours and minutes as accurate as possible",
"hour"=> "HOUR",
"mins"=> "MIN",
"phone"=> "Phone number",

//EMAILs PAGES
"confidence"=> 'Do not forget about this VERY SPECIAL GIFT that the forces of Light have asked me to send you. It could be yours RIGHT NOW!',

//month
"March"=> "Mar",
"April"=> "Apr",
"May"=> "May",
"June"=> "Jun",
"July"=> "Jul",
"August"=> "Aug",
"September"=> "Sep",
"October"=> "Oct",
"November"=> "Nov",
"December"=> "Dec",
"January"=> "Jan",
"February"=> "Feb",
'montharray'=> array(
"January",
"February",
"March",
"April",
"May",
"June",
"July",
"August",
"September",
"October",
"November",
"December"),
'daysarray'=> array("Mandag","Tirsdag","Onsdag","Torsdag","Fredag","Lørdag","Søndag"),

];
