<h2>Privacy Policy</h2>
    <p>DISCLAIMER: THE INFORMATION PROVIDED, WHETHER FREE OR PAID, MUST NOT BE CONSIDERED AS INDICATING AN OPINION IN THE REALMS OF PSYCHOLOGY, ECONOMY-FINANCE, MEDICINE, LEGAL MATTERS, REAL ESTATE OR OTHERS AND MUST IN NO CASE BE USED AS A BASIS FOR DECISION MAKING. TESTIMONIALS, REVIEWS AND ENDORSEMENTS ARE FREE INDIVIDUAL OPINIONS THAT IN NO CASE IMPLY IDENTICAL RESULTS FOR EVERYBODY. PLEASE ALSO READ THE TERMS OF USE.</p><br><br>
    <p>Futurastro, 1 Ward Bingleystraat 1065 TJ Amsterdam.</p>
    <br>
