<p>{{ print_dynamic_variable('address') }}<br><br>
Wenn Sie im Europäischen Wirtschaftsraum („EWR“) ansässig sind, haben Sie bestimmte Datenschutzrechte und wir werden uns bemühen, angemessene Schritte zu unternehmen, damit Sie die Nutzung Ihrer personenbezogenen Daten korrigieren, ändern, löschen oder einschränken können . Wenn Sie wissen möchten, welche personenbezogenen Daten wir über Sie gespeichert haben, und wenn Sie möchten, dass diese aus unseren Systemen entfernt werden, kontaktieren Sie uns bitte. Ihnen stehen unter Umständen folgende Datenschutzrechte zu:<br><br>
    (i) Sie haben das Recht, Ihre Einwilligung zu widerrufen, wenn Sie zuvor der Verarbeitung Ihrer personenbezogenen Daten zugestimmt haben. Soweit die Rechtsgrundlage für unsere Verarbeitung Ihrer personenbezogenen Daten die Einwilligung ist, haben Sie das Recht, diese Einwilligung jederzeit zu widerrufen. Der Widerruf berührt nicht die Rechtmäßigkeit der bis zum Widerruf erfolgten Verarbeitung.<br><br>
    (ii) Sie haben das Recht zu erfahren, ob Ihre personenbezogenen Daten von uns verarbeitet werden, Informationen über bestimmte Aspekte der Verarbeitung zu erhalten und eine Kopie Ihrer verarbeiteten personenbezogenen Daten zu erhalten.<br><br>
    (iii) Sie haben das Recht, die Richtigkeit Ihrer Informationen zu überprüfen und zu verlangen, dass sie aktualisiert oder korrigiert werden. Sie haben auch das Recht zu verlangen, dass wir alle personenbezogenen Daten vervollständigen, die Sie für unvollständig halten.<br><br>
    (iv) Sie haben das Recht, der Verarbeitung Ihrer Daten zu widersprechen, wenn die Verarbeitung auf einer anderen Rechtsgrundlage als der Einwilligung beruht. Wenn personenbezogene Daten im öffentlichen Interesse, in Ausübung einer uns übertragenen behördlichen Befugnis oder für die von uns verfolgten berechtigten Interessen verarbeitet werden, können Sie dieser Verarbeitung aus einem bestimmten situationsbezogenen Grund widersprechen, um den Widerspruch zu rechtfertigen. Sie sollten jedoch wissen, dass Sie, wenn Ihre personenbezogenen Daten für Direktmarketingzwecke verarbeitet werden, dieser Verarbeitung jederzeit ohne Angabe von Gründen widersprechen können. Um herauszufinden, ob wir personenbezogene Daten für Direktmarketingzwecke verarbeiten, lesen Sie bitte die entsprechenden Abschnitte dieser Richtlinie.<br><br>
    (v) Sie haben unter bestimmten Umständen das Recht, die Verarbeitung Ihrer personenbezogenen Daten einzuschränken. Zu diesen Umständen gehören: Die Richtigkeit Ihrer personenbezogenen Daten wird von Ihnen bestritten und wir müssen ihre Richtigkeit überprüfen; die Verarbeitung unrechtmäßig ist, Sie aber die Löschung Ihrer personenbezogenen Daten ablehnen und stattdessen die Einschränkung ihrer Verwendung verlangen; Wir benötigen Ihre personenbezogenen Daten für die Zwecke der Verarbeitung nicht mehr, Sie benötigen sie jedoch zur Geltendmachung, Ausübung oder Verteidigung Ihrer Rechtsansprüche; Sie haben der Verarbeitung widersprochen, bis überprüft wurde, ob unsere berechtigten Gründe Vorrang vor Ihren berechtigten Gründen haben. Wenn die Verarbeitung eingeschränkt ist, werden diese personenbezogenen Daten entsprechend gekennzeichnet und mit Ausnahme der Speicherung nur mit Ihrer Einwilligung oder zur Geltendmachung, Ausübung oder Verteidigung von Rechtsansprüchen, zum Schutz der Rechte einer anderen natürlichen oder juristischen Person oder verarbeitet aus Gründen des großen öffentlichen Interesses.<br><br>
    (vi) Sie haben unter bestimmten Umständen das Recht, Ihre personenbezogenen Daten von uns löschen zu lassen. Zu diesen Umständen gehören: Die personenbezogenen Daten sind für die Zwecke, für die sie erhoben oder anderweitig verarbeitet wurden, nicht mehr erforderlich; Sie widerrufen Ihre Einwilligung zur einwilligungsbasierten Verarbeitung; Sie widersprechen der Verarbeitung nach bestimmten Regeln des anwendbaren Datenschutzrechts; die Verarbeitung dient Direktmarketingzwecken; und die personenbezogenen Daten unrechtmäßig verarbeitet wurden. Es gibt jedoch Ausnahmen vom Recht auf Löschung, etwa wenn die Verarbeitung erforderlich ist: zur Ausübung des Rechts auf freie Meinungsäußerung und Information; um einer gesetzlichen Verpflichtung nachzukommen; oder zur Geltendmachung, Ausübung oder Verteidigung eines Rechtsanspruchs.<br><br>
    (vii) Sie haben das Recht, Ihre personenbezogenen Daten, die Sie uns bereitgestellt haben, in einem strukturierten, gängigen und maschinenlesbaren Format zu erhalten und, sofern technisch machbar, ohne Behinderung unsererseits an einen anderen Verantwortlichen übertragen zu lassen dass eine solche Übertragung die Rechte und Freiheiten anderer Personen nicht beeinträchtigt.<br><br>
    (viii) Sie haben das Recht, bei einer Datenschutzbehörde eine Beschwerde über unsere Erfassung und Verwendung Ihrer personenbezogenen Daten einzureichen. Wenn Sie mit dem Ergebnis Ihrer Beschwerde direkt bei uns nicht zufrieden sind, haben Sie das Recht, eine Beschwerde bei Ihrer örtlichen Datenschutzbehörde einzureichen. Für weitere Informationen wenden Sie sich bitte an Ihre lokale Datenschutzbehörde im EWR. Diese Bestimmung gilt unter der Voraussetzung, dass Ihre personenbezogenen Daten automatisiert verarbeitet werden und die Verarbeitung auf Ihrer Einwilligung, auf einem Vertrag, an dem Sie beteiligt sind, oder auf vorvertraglichen Verpflichtungen davon beruht.<br><br>
    Hinweis: Wenn Sie die E-Mail nicht erhalten, überprüfen Sie bitte Ihren Spam.<br><br>
    1) Senden Sie Ihre Nachricht an <a href="mailto:dpo@mg.astrology-prism.com" class="text-decoration-none">dpo@mg.astrology-prism.com</a> <br><br>
    2) Damit wir Ihre Informationen finden können, geben Sie bitte Folgendes an:<br>
    &emsp;Vorname: :<br>
    &emsp;Nachname:<br>
    &emsp;Geburtsdatum:(dd/mm/yyyy):<br>
    &emsp;E-Mail :<br>
    &emsp;Telefon :<br><br>
    3) Bitte reichen Sie Ihre Anfrage mit folgendem Grund ein:<br>

    &emsp;- Auskunftsrecht<br>
    &emsp;- Widerrufsrecht<br>
    &emsp;- Recht auf Löschung („Recht auf Vergessenwerden“) (Beispiel: Löschung personenbezogener Daten, Kontoschließung etc.)<br>
    &emsp;- Erbrecht<br>
    &emsp;- Widerspruchsrecht<br>
    &emsp;- Andere Anfrage<br>
</p>
