<?php

function print_dynamic_variable($var): string
{
    $dynamic = [
        
        'disclaimer_title_en' => 'DISCLAIMER',
        'disclaimer_text_en' => '
                    DISCLAIMER: THE INFORMATION PROVIDED SHOULD NOT BE CONSIDERED AS PSYCHOLOGICAL, MEDICAL, ECONOMIC-FINANCIAL, REAL ESTATE, LEGAL ADVICE OR OTHER AND SHOULD IN NO EVENT BE USED AS A BASIS FOR DECISION-MAKING, BUT FOR PURPOSES OF ENTERTAINMENT, WHETHER FREE OR PAID.
                    <br><br>
                    TESTIMONIALS, REVIEWS AND COMMENTS ARE INDIVIDUAL OPINIONS, WHICH DO NOT MEAN THAT ALL PEOPLE ACHIEVE SIMILAR RESULTS. PLEASE READ THE TERMS AND CONDITIONS.<br><br>
        ',

        'disclaimer_title_es' => 'DESCARGO DE RESPONSABILIDAD',
        'disclaimer_text_es' => '
                    DESCARGO DE RESPONSABILIDAD: LA INFORMACIÓN FACILITADA NO DEBE CONSIDERARSE ASESORAMIENTO PSICOLÓGICO, MÉDICO, ECONÓMICO-FINANCIERO, INMOBILIARIO, JURÍDICO O DE OTRO TIPO Y EN NINGÚN CASO DEBE UTILIZARSE COMO BASE PARA LA TOMA DE DECISIONES, SINO CON FINES DE ENTRETENIMIENTO, YA SEA GRATUITO O DE PAGO.
                    <br><br>
                    LOS TESTIMONIOS, RESEÑAS Y COMENTARIOS SON OPINIONES INDIVIDUALES, LO QUE NO SIGNIFICA QUE TODAS LAS PERSONAS OBTENGAN RESULTADOS SIMILARES. LEA LAS CONDICIONES GENERALES.<br><br>
        ',

        'disclaimer_title_nl' => 'DISCLAIMER',
        'disclaimer_text_nl' => '
                    DISCLAIMER: DE VERSTREKTE INFORMATIE MAG NIET WORDEN BESCHOUWD ALS PSYCHOLOGISCH, MEDISCH, ECONOMISCH-FINANCIEEL, ONROEREND GOED, JURIDISCH OF ANDER ADVIES EN MAG IN GEEN GEVAL WORDEN GEBRUIKT ALS BASIS VOOR BESLUITVORMING, MAAR DIENT TER VERMAAK, GRATIS OF BETAALD.
                    <br><br>
                    GETUIGENISSEN, BEOORDELINGEN EN OPMERKINGEN ZIJN INDIVIDUELE MENINGEN, DIE NIET BETEKENEN DAT ALLE MENSEN VERGELIJKBARE RESULTATEN BEHALEN. LEES DE ALGEMENE VOORWAARDEN.<br><br>
        ',

        'disclaimer_title_pt' => 'ISENÇÃO DE RESPONSABILIDADE',
        'disclaimer_text_pt' => '
                    ISENÇÃO DE RESPONSABILIDADE: AS INFORMAÇÕES FORNECIDAS NÃO DEVEM SER CONSIDERADAS COMO ACONSELHAMENTO PSICOLÓGICO, MÉDICO, ECONÓMICO-FINANCEIRO, IMOBILIÁRIO, JURÍDICO OU OUTRO E NÃO DEVEM, EM CASO ALGUM, SER UTILIZADAS COMO BASE PARA A TOMADA DE DECISÕES, MAS SIM PARA FINS DE ENTRETENIMENTO, GRATUITO OU PAGO.
                    <br><br>
                    OS TESTEMUNHOS, CRÍTICAS E COMENTÁRIOS SÃO OPINIÕES INDIVIDUAIS, O QUE NÃO SIGNIFICA QUE TODAS AS PESSOAS OBTENHAM RESULTADOS SEMELHANTES. LEIA OS TERMOS E CONDIÇÕES.<br><br>
        ',

        'disclaimer_title_fr' => 'AVERTISSEMENT',
        'disclaimer_text_fr' => '
                    AVERTISSEMENT : LES INFORMATIONS FOURNIES NE DOIVENT PAS ÊTRE CONSIDÉRÉES COMME DES CONSEILS PSYCHOLOGIQUES, MÉDICAUX, ÉCONOMICO-FINANCIERS, IMMOBILIERS, JURIDIQUES OU AUTRES ET NE DOIVENT EN AUCUN CAS ÊTRE UTILISÉES COMME BASE DE DÉCISION, MAIS À DES FINS DE DIVERTISSEMENT, QU\'ELLES SOIENT GRATUITES OU PAYANTES.
                    <br><br>
                    LES TÉMOIGNAGES, LES CRITIQUES ET LES COMMENTAIRES SONT DES OPINIONS INDIVIDUELLES, QUI NE SIGNIFIENT PAS QUE TOUTES LES PERSONNES OBTIENNENT DES RÉSULTATS SIMILAIRES. VEUILLEZ LIRE LES CONDITIONS GÉNÉRALES.<br><br>
        ',

        'disclaimer_title_de' => 'HAFTUNGSAUSSCHLUSS',
        'disclaimer_text_de' => '
                    HAFTUNGSAUSSCHLUSS: DIE BEREITGESTELLTEN INFORMATIONEN SOLLTEN NICHT ALS PSYCHOLOGISCHE, MEDIZINISCHE, WIRTSCHAFTLICH-FINANZIELLE, IMMOBILIEN-, RECHTS- ODER ANDERE BERATUNG BETRACHTET WERDEN UND SOLLTEN AUF KEINEN FALL ALS ENTSCHEIDUNGSGRUNDLAGE DIENEN, SONDERN ZU UNTERHALTUNGSZWECKEN, OB KOSTENLOS ODER BEZAHLT.
                    <br><br>
                    ZEUGNISSE, BEWERTUNGEN UND KOMMENTARE SIND INDIVIDUELLE MEINUNGEN, DIE NICHT BEDEUTEN, DASS ALLE MENSCHEN ÄHNLICHE ERGEBNISSE ERZIELEN. BITTE LESEN SIE DIE BEDINGUNGEN UND KONDITIONEN.<br><br>
        ',
        'disclaimer_title_it' => 'DICHIARAZIONE DI NON RESPONSABILITÀ',
        'disclaimer_text_it' => '
                    DICHIARAZIONE DI NON RESPONSABILITÀ: LE INFORMAZIONI FORNITE NON DOVREBBERO ESSERE CONSIDERATE COME CONSIGLI PSICOLOGICI, MEDICI, ECONOMICO-FINANZIARI, IMMOBILIARI, LEGALI O ALTRO, E NON DOVREBBERO ESSERE UTILIZZATE IN ALCUN CASO COME BASE PER LA PRESA DI DECISIONI, MA A SCOPO DI INTRATTENIMENTO, SIA GRATUITO CHE A PAGAMENTO.
                    <br><br>
                    LE TESTIMONIANZE, LE RECENSIONI E I COMMENTI SONO OPINIONI INDIVIDUALI, CHE NON IMPLICANO CHE TUTTE LE PERSONE RAGGIUNGANO RISULTATI SIMILI. SI PREGA DI LEGGERE I TERMINI E LE CONDIZIONI.<br><br>
        ',

        'address' => 'Astro Veo, Keizersgracht 520 H, 1017EK Amsterdam.',

    ];
    return $dynamic[$var];
}
